apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: claude-gateway-secret
  namespace: claude-gateway
spec:
    data:
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: OIDC-CLIENT-SECRET
          metadataPolicy: None
        secretKey: OIDC_CLIENT_SECRET
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: GATEWAY-JWT-SECRET
          metadataPolicy: None
        secretKey: GATEWAY_JWT_SECRET 
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: GATEWAY-ADMIN-READ-KEY
          metadataPolicy: None
        secretKey: GATEWAY_ADMIN_READ_KEY
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: GATEWAY-ADMIN-WRITE-KEY
          metadataPolicy: None
        secretKey: GATEWAY_ADMIN_WRITE_KEY 
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: CLAUDE-PG-USER
          metadataPolicy: None
        secretKey: CLAUDE_PG_USER 
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: CLAUDE-PG-PASSWORD
          metadataPolicy: None
        secretKey: CLAUDE_PG_PASSWORD
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: AWS-ACCESS-KEY-ID
          metadataPolicy: None
        secretKey: AWS_ACCESS_KEY_ID
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: AWS-SECRET-ACCESS-KEY
          metadataPolicy: None
        secretKey: AWS_SECRET_ACCESS_KEY
    refreshInterval: 1h0m0s
    secretStoreRef:
      kind: SecretStore
      name: claude-gateway-secrets
    target:
      creationPolicy: Owner
      deletionPolicy: Retain
      name: claude-gateway-secrets