apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: claude-gateway-secrets
  namespace: claude-gateway
spec:
  provider:
    azurekv:
      authSecretRef:
        clientId:
          key: clientid
          name: gov-kv-secret
        clientSecret:
          key: clientsecret
          name: gov-kv-secret
      authType: ServicePrincipal
      environmentType: USGovernmentCloud
      tenantId: ad852420-b06d-428c-9fbb-01e6d52a5b74
      vaultUrl: "https://claude-gateway.vault.usgovcloudapi.net/"