apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: la4-store
  namespace: claude-gateway
spec:
  configuration:
      destinationPath: s3://cnpg-backup-devops/
      endpointURL: http://10.18.2.94:80
      s3Credentials:
        accessKeyId:
          name: objectstore-secrets
          key: LA4_OBJECTSTORE_ID
        secretAccessKey:
          name: objectstore-secrets
          key: LA4_OBJECTSTORE_KEY
      wal:        
        compression: snappy
  retentionPolicy: "30d"